import Head from 'next/head';
import { styled } from 'styled-components';
import ArticleCard from '~/components/article-card';

const ArticleList = styled.ul`
  padding: 28px 20px;
  display: flex;
  flex-direction: column;
  gap: 4px;
  background: var(--Gray7, #f9f7f5);
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>vocus F2E challenge</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='https://vocus.cc/static/favicon.ico' />
      </Head>
      <main>
        <ArticleList>
          <ArticleCard />
        </ArticleList>
      </main>
    </>
  );
}
