import Head from 'next/head';
// import localFont from 'next/font/local';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

export default function Home() {
  return (
    <>
      <Head>
        <title>vocus F2E challenge</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='https://vocus.cc/static/favicon.ico' />
      </Head>
      <div>index</div>
    </>
  );
}
